version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: dblint-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5432:5432"
